# Generated by Django 5.1.4 on 2026-08-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=160)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('etablissement_scolaire', models.CharField(blank=True, max_length=180)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('passions', models.JSONField(blank=True, default=list)),
                ('preference_universites', models.CharField(blank=True, max_length=260)),
                ('preference_secteur', models.CharField(blank=True, max_length=20)),
                ('preference_mode_entree', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serie_bac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.seriebac')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidats.candidat')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.matiere')),
            ],
            options={
                'ordering': ['matiere__nom'],
                'unique_together': {('candidat', 'matiere')},
            },
        ),
    ]
