# Generated by Django 5.1.4 on 2026-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='annee_bac',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='candidat',
            name='commune',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='departement',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin'), ('A', 'Autre')], max_length=1),
        ),
        migrations.AddField(
            model_name='candidat',
            name='type_candidat',
            field=models.CharField(choices=[('nouveau_bachelier', 'Nouveau bachelier'), ('ancien_bachelier', 'Ancien bachelier'), ('parent_tuteur', 'Parent ou tuteur')], default='nouveau_bachelier', max_length=30),
        ),
    ]
