# Generated by Django 6.0.4 on 2026-08-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0002_candidat_annee_bac_candidat_commune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='etablissement_scolaire',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='preference_universites',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='ville',
        ),
    ]
