# Generated by Codex on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidats", "0003_remove_candidat_etablissement_scolaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidat",
            name="diplome_examen",
            field=models.CharField(
                choices=[("BAC", "BAC"), ("DEAT", "DEAT"), ("DT", "DT")],
                default="BAC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="candidat",
            name="option_diplome",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
