# Generated by Django 5.1.4 on 2026-08-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('nom', models.CharField(max_length=220)),
                ('type', models.CharField(choices=[('public_universite', 'Université publique'), ('public_ecole_inter_etats', 'École inter-États'), ('prive_epes', 'EPES privé'), ('semecity', 'Sèmè City')], max_length=40)),
                ('logo', models.ImageField(blank=True, upload_to='logos/categories/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "catégorie d'établissement",
                'verbose_name_plural': "catégories d'établissements",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=260)),
                ('sigle', models.CharField(blank=True, max_length=80)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('secteur', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé')], default='public', max_length=12)),
                ('regime', models.CharField(choices=[('agree', 'Agréé'), ('en_ouverture', 'En ouverture'), ('na', 'Non applicable')], default='na', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to='catalogue.categorieetablissement')),
            ],
            options={
                'ordering': ['categorie__id', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=260)),
                ('diplome', models.CharField(choices=[('licence', 'Licence'), ('licence_professionnelle', 'Licence professionnelle'), ('bapes', 'BAPES'), ('classe_preparatoire', 'Classe préparatoire'), ('autre', 'Autre')], default='licence', max_length=40)),
                ('mode_entree', models.CharField(choices=[('classement', 'Classement'), ('concours', 'Concours'), ('dossier', 'Dossier')], default='classement', max_length=20)),
                ('quota_bourse', models.PositiveIntegerField(default=0)),
                ('quota_aide_fpp', models.PositiveIntegerField(default=0)),
                ('debouches', models.TextField(blank=True)),
                ('regime', models.CharField(choices=[('agree', 'Agréé'), ('en_ouverture', 'En ouverture'), ('na', 'Non applicable')], default='na', max_length=20)),
                ('seuil_bourse_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('seuil_aide_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mots_cles', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules pour les passions.', max_length=300)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='catalogue.etablissement')),
            ],
            options={
                'ordering': ['etablissement__nom', 'intitule'],
            },
        ),
        migrations.CreateModel(
            name='SerieBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=160)),
                ('famille', models.CharField(choices=[('litteraire', 'Littéraire'), ('scientifique', 'Scientifique'), ('technique', 'Technique'), ('agricole', 'Agricole'), ('economique', 'Économique'), ('toutes', 'Toutes')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_options', to='catalogue.seriebac')),
            ],
            options={
                'verbose_name': 'série de BAC',
                'verbose_name_plural': 'séries de BAC',
                'ordering': ['famille', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FiliereSerieRecommandee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_recommandees', to='catalogue.filiere')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filieres_recommandees', to='catalogue.seriebac')),
            ],
            options={
                'verbose_name': 'série recommandée',
                'verbose_name_plural': 'séries recommandées',
                'unique_together': {('filiere', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=220)),
                ('sigle', models.CharField(blank=True, max_length=40)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universites', to='catalogue.categorieetablissement')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='universite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='catalogue.universite'),
        ),
        migrations.CreateModel(
            name='MatiereClassement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=1)),
                ('filiere_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classement', to='catalogue.filiereserierecommandee')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.matiere')),
            ],
            options={
                'verbose_name': 'matière de classement',
                'verbose_name_plural': 'matières de classement',
                'ordering': ['ordre_affichage', 'matiere__nom'],
                'unique_together': {('filiere_serie', 'matiere')},
            },
        ),
    ]
