# Generated by Django 5.1.4 on 2026-08-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieMatiereCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=1)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coefficients_series', to='catalogue.matiere')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients_bac', to='catalogue.seriebac')),
            ],
            options={
                'verbose_name': 'coefficient BAC par série',
                'verbose_name_plural': 'coefficients BAC par série',
                'ordering': ['serie__code', 'ordre_affichage', 'matiere__nom'],
                'unique_together': {('serie', 'matiere')},
            },
        ),
    ]
